# Generated by Django 2.2.3 on 2019-08-13 17:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import favorita.forms


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0040_auto_20190804_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', favorita.forms.MyDateField(default=django.utils.timezone.now)),
                ('population_size', models.IntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)])),
                ('number_iterations', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('mutation_rate', favorita.forms.MinMaxFloat(default=0.5)),
                ('crossing_rate', favorita.forms.MinMaxFloat(default=0.5)),
                ('failed_attempts_stop', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_time', models.IntegerField(blank=True, default=0, null=True)),
                ('best_fitness', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('errors', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='fitness_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
